//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution_1_Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheapest_currency
    {
        public int featureid { get; set; }
        public System.Guid globalid { get; set; }
        public string symbol { get; set; }
        public Nullable<double> amount { get; set; }
    }
}
